### ISSUE TITLE
inmobi ads don't appear after updating sdk to 9.0.2

### ISSUE THREAD

**Issue by Asmaa-k** [InMobi/sdk-sample-code-android#54]
E: java.lang.NoSuchMethodError: No static method init(Landroid/content/Context;Ljava/lang/String;Lorg/json/JSONObject;)V in class Lcom/inmobi/sdk/InMobiSdk; or its super classes (declaration of 'com.inmobi.sdk.InMobiSdk' appears in /data/app/com.opensooq.OpenSooq-Obg82DTnyPznIB-wz0suqg==/base.apk:classes17.dex)
        at com.google.ads.mediation.inmobi.InMobiAdapter.requestBannerAd(InMobiAdapter.java:130)
        at com.google.android.gms.internal.ads.zzaly.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:45)
        at com.google.android.gms.internal.ads.zzalg.zza(com.google.android.gms:play-services-ads-lite@@18.3.0:56)
        at com.google.android.gms.internal.ads.zzgb.onTransact(com.google.android.gms:play-services-ads-base@@18.3.0:13)
        at android.os.Binder.transact(Binder.java:612)
        at fe.b(:com.google.android.gms.policy_ads_fdr_dynamite@21207004@21207004.283464268.283464268:2)
        at com.google.android.gms.ads.internal.mediation.client.e.a(:com.google.android.gms.policy_ads_fdr_dynamite@21207004@21207004.283464268.283464268:9)
        at com.google.android.gms.ads.nonagon.render.u.a(:com.google.android.gms.policy_ads_fdr_dynamite@21207004@21207004.283464268.283464268:16)
        at com.google.android.gms.ads.nonagon.render.df.a(Unknown Source:10)
        at com.google.android.gms.ads.nonagon.util.concurrent.s.call(Unknown Source:2)
        at xw.a(:com.google.android.gms.policy_ads_fdr_dynamite@21207004@21207004.283464268.283464268:1)
        at xh.run(:com.google.android.gms.policy_ads_fdr_dynamite@21207004@21207004.283464268.283464268:7)
        at xx.run(:com.google.android.gms.policy_ads_fdr_dynamite@21207004@21207004.283464268.283464268:1)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at oz.a(Unknown Source:0)
        at com.google.android.gms.ads.internal.util.f.a(:com.google.android.gms.policy_ads_fdr_dynamite@21207004@21207004.283464268.283464268:1)
        at oz.dispatchMessage(Unknown Source:0)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by SwagatoMondal** [comment]
Hi @Asmaa-k This is a known issue, Google has updated their [adapters](https://github.com/googleads/googleads-mobile-android-mediation/blob/e206f0c1196f8f9cf9144ae07bf26f3cd2d92955/ThirdPartyAdapters/inmobi/inmobi/build.gradle#L42) to support **InMobi Android SDK v902** recently. But I'm not sure if the adapters are released yet, in the meantime do stick to **v901** of our SDK. The moment you see Google has pushed their adapter version `9.0.2.0`, you can update InMobi SDK to **902**.

**Comment by SwagatoMondal** [comment]
Closing issue as Google has released latest InMobi adapters.
